services:
  # https://grafana.com/blog/an-opentelemetry-backend-in-a-docker-image-introducing-grafana-otel-lgtm/
  otel-lgtm:
    image: grafana/otel-lgtm:0.15.0
    ports:
      - 3000:3000 # Grafana UI
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
